"""linha de base: schema completo do RunRate

Revision ID: f84a5532d045
Revises: 
Create Date: 2026-08-26 11:20:43.651094
"""
from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel  # os campos str do SQLModel viram sqlmodel.sql.sqltypes.AutoString
from alembic import op


revision: str = 'f84a5532d045'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cliente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('contato', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('configuracao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome_consultoria', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('cnpj', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('jornada_semanal', sa.Float(), nullable=False),
    sa.Column('limiar_super', sa.Float(), nullable=False),
    sa.Column('limiar_ocioso', sa.Float(), nullable=False),
    sa.Column('meta_margem', sa.Float(), nullable=False),
    sa.Column('taxa_junior', sa.Float(), nullable=False),
    sa.Column('taxa_pleno', sa.Float(), nullable=False),
    sa.Column('taxa_senior', sa.Float(), nullable=False),
    sa.Column('formato_data', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('moeda', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('fuso', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('taxa_km', sa.Float(), nullable=False),
    sa.Column('anthropic_api_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('modelo_ia', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('consultor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('senioridade', sa.Enum('junior', 'pleno', 'senior', name='senioridade'), nullable=False),
    sa.Column('modulo_sap', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('skills', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('taxa_hora_custo', sa.Float(), nullable=False),
    sa.Column('taxa_hora_venda', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('eventoauditoria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quando', sa.DateTime(), nullable=False),
    sa.Column('usuario', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('perfil', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('metodo', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('caminho', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('detalhe', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('feriado',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('nome', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('modeloprojeto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('descricao', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('padrao', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tentativalogin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('quando', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tentativalogin_email'), 'tentativalogin', ['email'], unique=False)
    op.create_table('ausencia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('consultor_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Enum('ferias', 'folga', 'afastamento', 'treinamento', name='tipoausencia'), nullable=False),
    sa.Column('data_inicio', sa.Date(), nullable=False),
    sa.Column('data_fim', sa.Date(), nullable=False),
    sa.Column('motivo', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sa.Enum('pendente', 'aprovada', 'recusada', name='statusaprovacao'), nullable=False),
    sa.Column('comentario_gestor', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['consultor_id'], ['consultor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contrato',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('nome', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('data_inicio', sa.Date(), nullable=False),
    sa.Column('data_fim', sa.Date(), nullable=False),
    sa.Column('valor', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('vigente', 'encerrado', 'cancelado', name='statuscontrato'), nullable=False),
    sa.Column('observacoes', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('enviosemana',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('consultor_id', sa.Integer(), nullable=False),
    sa.Column('semana', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('enviada', 'aprovada', 'reprovada', name='statusenvio'), nullable=False),
    sa.Column('total_horas', sa.Float(), nullable=False),
    sa.Column('comentario_gestor', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('enviado_em', sa.Date(), nullable=True),
    sa.Column('decidido_em', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['consultor_id'], ['consultor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('modeloatividade',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('modelo_id', sa.Integer(), nullable=False),
    sa.Column('fase', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('titulo', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ordem', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['modelo_id'], ['modeloprojeto.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('modeloitemgate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('modelo_id', sa.Integer(), nullable=False),
    sa.Column('fase', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('codigo', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('pergunta', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('risco', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['modelo_id'], ['modeloprojeto.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('projeto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('data_inicio', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('ativo', 'pausado', 'encerrado', name='statusprojeto'), nullable=False),
    sa.Column('licoes_aprendidas', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('encerrado_em', sa.Date(), nullable=True),
    sa.Column('modelo_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], ),
    sa.ForeignKeyConstraint(['modelo_id'], ['modeloprojeto.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('nome', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('senha_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('perfil', sa.Enum('ceo', 'rh', 'consultor', name='perfilusuario'), nullable=False),
    sa.Column('consultor_id', sa.Integer(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['consultor_id'], ['consultor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuario_email'), 'usuario', ['email'], unique=True)
    op.create_table('despesa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('consultor_id', sa.Integer(), nullable=False),
    sa.Column('projeto_id', sa.Integer(), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('tipo', sa.Enum('deslocamento', 'alimentacao', 'hospedagem', 'quilometragem', 'outros', name='tipodespesa'), nullable=False),
    sa.Column('descricao', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('valor', sa.Float(), nullable=False),
    sa.Column('km', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('pendente', 'aprovada', 'recusada', 'reembolsada', name='statusdespesa'), nullable=False),
    sa.Column('comentario_gestor', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['consultor_id'], ['consultor.id'], ),
    sa.ForeignKeyConstraint(['projeto_id'], ['projeto.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fase',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('projeto_id', sa.Integer(), nullable=False),
    sa.Column('nome', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ordem', sa.Integer(), nullable=False),
    sa.Column('data_inicio_prevista', sa.Date(), nullable=False),
    sa.Column('data_fim_prevista', sa.Date(), nullable=False),
    sa.Column('baseline_inicio', sa.Date(), nullable=True),
    sa.Column('baseline_fim', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('nao_iniciada', 'em_andamento', 'concluida', name='statusfase'), nullable=False),
    sa.ForeignKeyConstraint(['projeto_id'], ['projeto.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fatura',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('projeto_id', sa.Integer(), nullable=False),
    sa.Column('competencia', sa.Date(), nullable=False),
    sa.Column('valor', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('prevista', 'emitida', 'recebida', 'cancelada', name='statusfatura'), nullable=False),
    sa.Column('numero', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('data_emissao', sa.Date(), nullable=True),
    sa.Column('data_vencimento', sa.Date(), nullable=True),
    sa.Column('data_recebimento', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['projeto_id'], ['projeto.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('itemorcamento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('projeto_id', sa.Integer(), nullable=False),
    sa.Column('categoria', sa.Enum('horas', 'despesas', 'terceiros', 'licencas', 'outros', name='categoriaorcamento'), nullable=False),
    sa.Column('descricao', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('valor_orcado', sa.Float(), nullable=False),
    sa.Column('valor_realizado', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['projeto_id'], ['projeto.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mudancacr',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('projeto_id', sa.Integer(), nullable=False),
    sa.Column('titulo', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('descricao', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('impacto_horas', sa.Float(), nullable=False),
    sa.Column('impacto_valor', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('aberta', 'aprovada', 'rejeitada', name='statusmudanca'), nullable=False),
    sa.Column('criada_em', sa.Date(), nullable=False),
    sa.Column('decidida_em', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['projeto_id'], ['projeto.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('proposta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('nome', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('descricao', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('escopo', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('premissas', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('horas_junior', sa.Float(), nullable=False),
    sa.Column('horas_pleno', sa.Float(), nullable=False),
    sa.Column('horas_senior', sa.Float(), nullable=False),
    sa.Column('valor_estimado', sa.Float(), nullable=False),
    sa.Column('margem_estimada', sa.Float(), nullable=False),
    sa.Column('horas_estimadas', sa.Float(), nullable=False),
    sa.Column('probabilidade', sa.Float(), nullable=False),
    sa.Column('validade', sa.Date(), nullable=True),
    sa.Column('estagio', sa.Enum('qualificacao', 'proposta', 'negociacao', 'aprovada', 'perdida', 'convertida', name='estagioproposta'), nullable=False),
    sa.Column('criada_em', sa.Date(), nullable=False),
    sa.Column('decidida_em', sa.Date(), nullable=True),
    sa.Column('projeto_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], ),
    sa.ForeignKeyConstraint(['projeto_id'], ['projeto.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('risco',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('projeto_id', sa.Integer(), nullable=False),
    sa.Column('titulo', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('probabilidade', sa.Enum('baixo', 'medio', 'alto', name='graurisco'), nullable=False),
    sa.Column('impacto', sa.Enum('baixo', 'medio', 'alto', name='graurisco'), nullable=False),
    sa.Column('resposta', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sa.Enum('aberto', 'mitigado', 'materializado', name='statusrisco'), nullable=False),
    sa.ForeignKeyConstraint(['projeto_id'], ['projeto.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sessaoacesso',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('criada_em', sa.DateTime(), nullable=False),
    sa.Column('expira_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sessaoacesso_token'), 'sessaoacesso', ['token'], unique=True)
    op.create_table('sprint',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('projeto_id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=False),
    sa.Column('nome', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('meta', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('data_inicio', sa.Date(), nullable=False),
    sa.Column('data_fim', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('planejada', 'ativa', 'encerrada', name='statussprint'), nullable=False),
    sa.Column('encerrada_em', sa.Date(), nullable=True),
    sa.Column('carry_over', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['projeto_id'], ['projeto.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('alocacao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('consultor_id', sa.Integer(), nullable=False),
    sa.Column('fase_id', sa.Integer(), nullable=False),
    sa.Column('data_inicio', sa.Date(), nullable=False),
    sa.Column('data_fim', sa.Date(), nullable=False),
    sa.Column('horas_semana', sa.Float(), nullable=False),
    sa.Column('taxa_hora_venda', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['consultor_id'], ['consultor.id'], ),
    sa.ForeignKeyConstraint(['fase_id'], ['fase.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('atividade',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fase_id', sa.Integer(), nullable=False),
    sa.Column('titulo', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ordem', sa.Integer(), nullable=False),
    sa.Column('responsavel_id', sa.Integer(), nullable=True),
    sa.Column('data_prevista', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('pendente', 'em_andamento', 'concluida', name='statusatividade'), nullable=False),
    sa.Column('sprint_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['fase_id'], ['fase.id'], ),
    sa.ForeignKeyConstraint(['responsavel_id'], ['consultor.id'], ),
    sa.ForeignKeyConstraint(['sprint_id'], ['sprint.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('itemgate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fase_id', sa.Integer(), nullable=False),
    sa.Column('codigo', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('pergunta', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('risco', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sa.Enum('nao_verificado', 'verde', 'amarelo', 'vermelho', name='statusgate'), nullable=False),
    sa.Column('plano_acao', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('responsavel', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['fase_id'], ['fase.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('medicao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('projeto_id', sa.Integer(), nullable=False),
    sa.Column('competencia', sa.Date(), nullable=False),
    sa.Column('total_horas', sa.Float(), nullable=False),
    sa.Column('total_valor', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('gerada', 'aceita', 'contestada', name='statusmedicao'), nullable=False),
    sa.Column('observacoes', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('criada_em', sa.Date(), nullable=False),
    sa.Column('decidida_em', sa.Date(), nullable=True),
    sa.Column('fatura_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['fatura_id'], ['fatura.id'], ),
    sa.ForeignKeyConstraint(['projeto_id'], ['projeto.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pendencia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('projeto_id', sa.Integer(), nullable=False),
    sa.Column('fase_id', sa.Integer(), nullable=True),
    sa.Column('titulo', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('descricao', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('responsavel_id', sa.Integer(), nullable=True),
    sa.Column('prioridade', sa.Enum('baixa', 'media', 'alta', name='prioridadependencia'), nullable=False),
    sa.Column('status', sa.Enum('aberta', 'em_andamento', 'resolvida', name='statuspendencia'), nullable=False),
    sa.Column('criada_em', sa.Date(), nullable=False),
    sa.Column('resolvida_em', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['fase_id'], ['fase.id'], ),
    sa.ForeignKeyConstraint(['projeto_id'], ['projeto.id'], ),
    sa.ForeignKeyConstraint(['responsavel_id'], ['consultor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('apontamento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alocacao_id', sa.Integer(), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('horas', sa.Float(), nullable=False),
    sa.Column('descricao', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['alocacao_id'], ['alocacao.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('solicitacaoalocacao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('consultor_id', sa.Integer(), nullable=False),
    sa.Column('fase_id', sa.Integer(), nullable=False),
    sa.Column('data_inicio', sa.Date(), nullable=False),
    sa.Column('data_fim', sa.Date(), nullable=False),
    sa.Column('horas_semana', sa.Float(), nullable=False),
    sa.Column('taxa_hora_venda', sa.Float(), nullable=True),
    sa.Column('justificativa', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('solicitante', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sa.Enum('pendente', 'aprovada', 'recusada', name='statusaprovacao'), nullable=False),
    sa.Column('comentario_gestor', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('criada_em', sa.Date(), nullable=False),
    sa.Column('decidida_em', sa.Date(), nullable=True),
    sa.Column('alocacao_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['alocacao_id'], ['alocacao.id'], ),
    sa.ForeignKeyConstraint(['consultor_id'], ['consultor.id'], ),
    sa.ForeignKeyConstraint(['fase_id'], ['fase.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('solicitacaoalocacao')
    op.drop_table('apontamento')
    op.drop_table('pendencia')
    op.drop_table('medicao')
    op.drop_table('itemgate')
    op.drop_table('atividade')
    op.drop_table('alocacao')
    op.drop_table('sprint')
    op.drop_index(op.f('ix_sessaoacesso_token'), table_name='sessaoacesso')
    op.drop_table('sessaoacesso')
    op.drop_table('risco')
    op.drop_table('proposta')
    op.drop_table('mudancacr')
    op.drop_table('itemorcamento')
    op.drop_table('fatura')
    op.drop_table('fase')
    op.drop_table('despesa')
    op.drop_index(op.f('ix_usuario_email'), table_name='usuario')
    op.drop_table('usuario')
    op.drop_table('projeto')
    op.drop_table('modeloitemgate')
    op.drop_table('modeloatividade')
    op.drop_table('enviosemana')
    op.drop_table('contrato')
    op.drop_table('ausencia')
    op.drop_index(op.f('ix_tentativalogin_email'), table_name='tentativalogin')
    op.drop_table('tentativalogin')
    op.drop_table('modeloprojeto')
    op.drop_table('feriado')
    op.drop_table('eventoauditoria')
    op.drop_table('consultor')
    op.drop_table('configuracao')
    op.drop_table('cliente')
    # ### end Alembic commands ###
